"""Contains a list of 100 business disciplines"""

BUSINESS_DISCIPLINES = [
    "Accounting",
    "Advertising",
    "Agricultural Business",
    "Arts Management",
    "Aviation Management",
    "Banking",
    "Broadcasting, Radio, TV Management",
    "Business Administration",
    "Business Analytics",
    "Business Communication",
    "Business Economics",
    "Business Ethics",
    "Business Information Systems",
    "Business Intelligence",
    "Business Journalism",
    "Business Law",
    "Business Management",
    "Business Statistics",
    "Casino Management",
    "Change Management",
    "Communication Technology",
    "Compensation and Benefits",
    "Construction Management Technology",
    "Consumer Behavior",
    "Corporate Finance",
    "Corporate Governance",
    "Corporate Social Responsibility",
    "Crisis Management",
    "Culinary Management",
    "Customer Relationship Management",
    "Dairy Management",
    "Data Analytics for Business",
    "Digital Marketing",
    "E-Business",
    "Economics",
    "Employee Relations",
    "Entrepreneurship",
    "Environmental Management",
    "Event Management",
    "Executive Leadership",
    "Export Management",
    "Fashion Marketing & Management",
    "Fashion Merchandising",
    "Finance",
    "Financial Planning",
    "Financial Strategy",
    "Global Business",
    "Health Insurance Claims Management",
    "Health Services Administration",
    "Hospitality Management",
    "Human Resource Management",
    "Industrial Management",
    "Industrial Relations",
    "Information Management",
    "Information Systems Management",
    "Innovation Management",
    "Insurance and Risk Management",
    "International Business",
    "International Management",
    "International Marketing",
    "International Public Relations",
    "International Studies",
    "Investments & Securities",
    "Labor Relations",
    "Leadership Theory",
    "Legal Secretary",
    "Library Science Assistant",
    "Logistics",
    "Management Accounting",
    "Management Consulting",
    "Management Information Systems",
    "Management Science",
    "Market Research",
    "Marketing",
    "Marketing Management",
    "Marketing Strategy",
    "Mergers & Acquisitions",
    "Nonprofit Management",
    "Operations Management",
    "Operations Research",
    "Organizational Behavior",
    "Organizational Innovation",
    "Organizational Leadership",
    "Organizational Strategy",
    "Payroll Administration",
    "People Management",
    "Personnel Administration",
    "Private Banking and Asset Management",
    "Production Management",
    "Project Management",
    "Public Administration",
    "Public Relations",
    "Purchasing and Supply Management",
    "Quality Management",
    "Range Management",
    "Real Estate Management",
    "Recreational Management",
    "Restaurant Management",
    "Retail Management",
    "Small Business Management",
]
